openapi: "3.0.1"
info:
  title: "Catalog"
  version: "0.2.0"
paths:
  /pets:
    get:
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pets"
      x-amazon-apigateway-integration:
        type: "http"
        httpMethod: "GET"
        uri: "https://petstore.swagger.io/v2/pet/findByStatus?status=available"
        passthroughBehavior: "when_no_match"
        responses:
          200:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "#set($inputRoot = $input.path('$'))\n[\n##TODO: Update\
                \ this foreach loop to reference array from input json\n#foreach($elem\
                \ in $inputRoot)\n {\n  \"id\" : $elem.id,\n  \"name\" : \"$elem.name\"\
                \n} \n#if($foreach.hasNext),#end\n#end\n]"
    options:
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      x-amazon-apigateway-integration:
        type: "mock"
        passthroughBehavior: "when_no_match"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
components:
  schemas:
    Pets:
      title: "Pets"
      type: "array"
      items:
        $ref: "#/components/schemas/Pet"
    Empty:
      title: "Empty Schema"
      type: "object"
    Pet:
      title: "Pet"
      type: "object"
      properties:
        id:
          type: "number"
        name:
          type: "string"
